import { useEffect, useRef, useState } from 'react'
import './App.css'
import { testVideoProvider, videoProviders } from './providers/videoProviders'

const films = testVideoProvider.listContent()
const invitedRoomCode = new URLSearchParams(location.search).get('room')?.toUpperCase() ?? ''
const guests = [
  { name: 'Maya Chen', initials: 'MC', color: 'coral', status: 'Watching with you' },
  { name: 'Ethan Brooks', initials: 'EB', color: 'blue', status: 'Joined 2 min ago' },
]

function App() {
  const [screen, setScreen] = useState(() => location.pathname.startsWith('/cinema/') || invitedRoomCode ? 'join' : 'home')
  const [roomName, setRoomName] = useState('Friday Night Movie 🍿')
  const [film, setFilm] = useState(films[0])
  const [maxPeople, setMaxPeople] = useState(6)
  const [permission, setPermission] = useState('Host only')
  const [cam, setCam] = useState(true)
  const [mic, setMic] = useState(true)
  const [code, setCode] = useState('AB7K92')
  const [mode, setMode] = useState('Cinema')
  const [playing, setPlaying] = useState(false)
  const [chatOpen, setChatOpen] = useState(false)
  const [peopleOpen, setPeopleOpen] = useState(false)
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [toast, setToast] = useState('')
  const [messages, setMessages] = useState([{ name: 'Maya', text: 'I brought snacks 🍿', time: '8:41' }, { name: 'You', text: 'Movie night is officially on.', time: '8:42' }])
  const [draft, setDraft] = useState('')
  const [reaction, setReaction] = useState('')
  const [joinCode, setJoinCode] = useState(() => invitedRoomCode || (location.pathname.startsWith('/cinema/') ? location.pathname.split('/').pop().toUpperCase() : ''))
  const [elapsed, setElapsed] = useState(81)
  const [duration, setDuration] = useState(540)
  const videoRef = useRef(null)
  const toastTimer = useRef(null)

  const notify = (text) => { setToast(text); clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setToast(''), 2400) }
  useEffect(() => () => clearTimeout(toastTimer.current), [])
  useEffect(() => {
    const onKey = (event) => { if (event.key === 'Escape') { setChatOpen(false); setPeopleOpen(false); setSettingsOpen(false) } }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [])
  const enterRoom = () => { setScreen('cinema'); setPlaying(false); setElapsed(0) }
  const togglePlayback = () => {
    const video = videoRef.current
    if (video) {
      if (video.paused) video.play().catch(() => notify('Video could not load. Check your connection.'))
      else video.pause()
    }
    setPlaying((value) => !value)
  }
  const sendMessage = (event) => {
    event.preventDefault()
    if (!draft.trim()) return
    setMessages((items) => [...items, { name: 'You', text: draft.trim(), time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }])
    setDraft('')
  }
  const sendReaction = (emoji) => { setReaction(emoji); setTimeout(() => setReaction(''), 1600) }
  const formatTime = (seconds) => `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`
  const inviteUrl = () => `${location.origin}${import.meta.env.BASE_URL}?room=${code}`

  if (screen === 'cinema') return <main className={`cinema-page mode-${mode.toLowerCase()}`}>
    <header className="cinema-top"><button className="back-button" onClick={() => { setScreen('home'); setPlaying(false); videoRef.current?.pause() }}>← <span>Leave cinema</span></button><div className="room-heading"><span className="live-dot"/> <div><b>{roomName}</b><small>Private cinema · <span>👑 You’re hosting</span></small></div></div><div className="top-actions"><button className="icon-button connection" title="Connection quality">◉ <span>Excellent</span></button><button className="invite-button" onClick={() => { navigator.clipboard?.writeText(inviteUrl()); notify('Invite link copied') }}>Invite friends <span>↗</span></button><button className="icon-button" onClick={() => setSettingsOpen(true)} aria-label="Room settings">⚙</button></div></header>
    <section className="cinema-stage">
      <div className="film-meta"><span className="provider-pill">{videoProviders[film.provider.toLowerCase().replace(' video', '')]?.name ?? film.provider}</span><b>{film.title}</b><small>{film.detail}</small></div>
      <div className="screen-wrap"><div className="movie-screen">
        <video ref={videoRef} src={film.src} playsInline preload="metadata" onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} onTimeUpdate={(e) => setElapsed(e.currentTarget.currentTime)} onLoadedMetadata={(e) => setDuration(e.currentTarget.duration || 540)} onClick={togglePlayback} poster="" />
        {!playing && <button className="big-play" onClick={togglePlayback} aria-label="Play movie">▶</button>}
        <div className="film-vignette"/>
      </div></div>
      {mode !== 'Focus' && <div className="friend-rail" aria-label="Friends in this cinema"><div className="camera-tile maya"><div className="avatar art-coral">MC</div><div className="tile-name"><span className="voice-dot"/> Maya <small>🎙</small></div><span className="tile-status">MAYA CHEN</span></div><div className="camera-tile ethan"><div className="avatar art-blue">EB</div><div className="tile-name">Ethan <small>🎙</small></div><span className="tile-status">ETHAN BROOKS</span></div></div>}
      <div className="reaction-float" aria-live="polite">{reaction}</div>
      <div className="movie-caption"><span className="sound-bars"><i/><i/><i/><i/></span><span>Maya is laughing</span></div>
    </section>
    <footer className="player-bar"><div className="playback"><button className="player-icon" onClick={togglePlayback} aria-label={playing ? 'Pause movie' : 'Play movie'}>{playing ? 'Ⅱ' : '▶'}</button><span className="timecode">{formatTime(elapsed)} <i>/</i> {formatTime(duration)}</span><input className="timeline" type="range" min="0" max={duration || 540} value={elapsed} onChange={(e) => { const time = Number(e.target.value); setElapsed(time); if (videoRef.current) videoRef.current.currentTime = time }} aria-label="Movie position"/><button className="player-icon volume" onClick={() => notify('Volume controls are on your device')} aria-label="Volume">◖))</button></div><div className="social-controls"><div className="emoji-row">{['❤️', '😂', '😭', '🔥', '😱'].map((emoji) => <button key={emoji} onClick={() => sendReaction(emoji)} aria-label={`React ${emoji}`}>{emoji}</button>)}</div><span className="control-divider"/><button className={`round-control ${mic ? '' : 'off'}`} onClick={() => setMic(!mic)} aria-label="Toggle microphone">{mic ? '♩' : '♩̸'}</button><button className={`round-control ${cam ? '' : 'off'}`} onClick={() => setCam(!cam)} aria-label="Toggle camera">{cam ? '◉' : '⊘'}</button><button className={`round-control ${chatOpen ? 'selected' : ''}`} onClick={() => { setChatOpen(!chatOpen); setPeopleOpen(false) }} aria-label="Open chat">▱<i className="unread-dot"/></button><button className={`round-control ${peopleOpen ? 'selected' : ''}`} onClick={() => { setPeopleOpen(!peopleOpen); setChatOpen(false) }} aria-label="Participants">♙<span className="people-count">3</span></button><button className="round-control" onClick={() => setSettingsOpen(true)} aria-label="Settings">⚙</button></div></footer>
    {chatOpen && <aside className="floating-panel chat-panel"><div className="panel-heading"><div><span className="panel-kicker">THE LOBBY</span><h2>Room chat <small>3</small></h2></div><button className="icon-button" onClick={() => setChatOpen(false)}>×</button></div><div className="message-list">{messages.map((message, index) => <div className="message" key={`${message.time}-${index}`}><div className={`mini-avatar ${message.name === 'Maya' ? 'art-coral' : message.name === 'You' ? 'art-violet' : 'art-blue'}`}>{message.name === 'Maya' ? 'MC' : message.name === 'You' ? 'TN' : 'EB'}</div><div><div className="message-top"><b>{message.name}</b><time>{message.time}</time></div><p>{message.text}</p></div></div>)}</div><form className="chat-compose" onSubmit={sendMessage}><input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Say something…" aria-label="Chat message"/><button type="submit" aria-label="Send message">↑</button></form></aside>}
    {peopleOpen && <aside className="floating-panel people-panel"><div className="panel-heading"><div><span className="panel-kicker">AROUND THE SCREEN</span><h2>In this cinema <small>3 / {maxPeople}</small></h2></div><button className="icon-button" onClick={() => setPeopleOpen(false)}>×</button></div><div className="participant-row"><div className="mini-avatar art-violet">TN</div><div><b>Tenzin Kalden <span className="host-tag">HOST</span></b><small>You · {mic ? 'Mic on' : 'Mic off'} · {cam ? 'Camera on' : 'Camera off'}</small></div><span className="participant-signal">●</span></div>{guests.map((guest) => <div className="participant-row" key={guest.name}><div className={`mini-avatar art-${guest.color}`}>{guest.initials}</div><div><b>{guest.name}</b><small>{guest.status} · Mic on</small></div><span className="participant-signal">●</span></div>)}<button className="panel-invite" onClick={() => notify('Invite link copied')}>＋ Invite someone</button></aside>}
    {settingsOpen && <div className="modal-backdrop" onClick={() => setSettingsOpen(false)}><section className="settings-modal" onClick={(e) => e.stopPropagation()}><div className="panel-heading"><div><span className="panel-kicker">MAKE IT YOURS</span><h2>Cinema settings</h2></div><button className="icon-button" onClick={() => setSettingsOpen(false)}>×</button></div><label className="setting-label">Viewing mode</label><div className="mode-picker">{['Cinema', 'Social', 'Focus'].map((item) => <button className={mode === item ? 'active' : ''} key={item} onClick={() => setMode(item)}><b>{item === 'Cinema' ? '▣' : item === 'Social' ? '▦' : '◫'}</b><span>{item}</span><small>{item === 'Cinema' ? 'Movie takes the stage' : item === 'Social' ? 'Bring friends closer' : 'Just the movie'}</small></button>)}</div><label className="setting-label">Who can control playback?</label><select value={permission} onChange={(e) => setPermission(e.target.value)}><option>Host only</option><option>Host + moderators</option><option>Everyone</option></select><div className="settings-note"><span>🔒</span><p>Your cinema is private. Only people with the invite link can join.</p></div><button className="danger-button" onClick={() => { setSettingsOpen(false); setScreen('home'); notify('Cinema ended for everyone') }}>End cinema for everyone</button></section></div>}
    {toast && <div className="toast-note">{toast}</div>}
  </main>

  if (screen === 'create') return <main className="setup-page"><header className="simple-top"><button className="brand-mark" onClick={() => setScreen('home')}>◉ <span>social cinema</span></button><span className="step-note">YOUR CINEMA, YOUR RULES</span></header><section className="setup-layout"><div className="setup-copy"><button className="text-back" onClick={() => setScreen('home')}>← Back to home</button><span className="eyebrow">MAKE IT A MOVIE NIGHT</span><h1>Set the scene.</h1><p>Pick a movie, gather your people, and make a little room for magic.</p><div className="setup-illustration"><span>✦</span><div className="illustration-window"><i/><i/><i/><b>▶</b></div><div className="seat seat-a">TN</div><div className="seat seat-b">MC</div><div className="seat seat-c">EB</div><small>YOUR PRIVATE CINEMA</small></div></div><div className="setup-form"><label className="field-label">Give your cinema a name<input value={roomName} onChange={(e) => setRoomName(e.target.value)} maxLength={40}/></label><div className="field-label">Choose what to watch <span className="field-hint">More providers coming soon</span></div><div className="film-options">{films.map((item) => <button className={`film-option ${film.id === item.id ? 'active' : ''}`} key={item.id} onClick={() => setFilm(item)}><div className={`film-art ${item.art}`}><span>{item.id === 'bbb' ? 'BUNNY' : 'STEEL'}</span><b>▶</b></div><span className="film-option-copy"><b>{item.title}</b><small>{item.detail}</small><em>✓ Licensed test video</em></span><span className="radio-check">{film.id === item.id ? '●' : '○'}</span></button>)}</div><div className="form-columns"><label className="field-label">Maximum guests<select value={maxPeople} onChange={(e) => setMaxPeople(Number(e.target.value))}>{[2,4,6,8].map(n => <option key={n} value={n}>{n} people</option>)}</select></label><label className="field-label">Playback controls<select value={permission} onChange={(e) => setPermission(e.target.value)}><option>Host only</option><option>Host + moderators</option><option>Everyone</option></select></label></div><div className="device-toggles"><div><span className="toggle-icon">▣</span><span><b>Camera</b><small>Let them see you</small></span><button className={`switch ${cam ? 'on' : ''}`} onClick={() => setCam(!cam)} aria-label="Toggle camera"/></div><div><span className="toggle-icon">♫</span><span><b>Microphone</b><small>Say hello when you arrive</small></span><button className={`switch ${mic ? 'on' : ''}`} onClick={() => setMic(!mic)} aria-label="Toggle microphone"/></div></div><button className="create-submit" onClick={() => setScreen('invite')}>Create your cinema <span>→</span></button><p className="form-legal">By creating a cinema, you agree to keep it cozy and kind.</p></div></section>{toast && <div className="toast-note">{toast}</div>}</main>

  if (screen === 'invite') return <main className="invite-page"><header className="simple-top"><button className="brand-mark" onClick={() => setScreen('home')}>◉ <span>social cinema</span></button><span className="step-note">CINEMA CREATED ✦</span></header><section className="invite-card"><div className="success-orbit">✦</div><span className="eyebrow">THE RED CARPET IS READY</span><h1>{roomName}</h1><p>Your cinema is ready. Send the invite and save them a seat.</p><div className="invite-preview"><div className={`film-art ${film.art}`}><span>{film.id === 'bbb' ? 'BUNNY' : 'STEEL'}</span></div><div><b>{film.title}</b><small>{film.detail} · {maxPeople} seats</small><span>◉ Private cinema</span></div><span className="preview-popcorn">🍿</span></div><div className="code-label">YOUR ROOM CODE</div><div className="room-code">{code.split('').map((letter, i) => <b key={i}>{letter}</b>)}</div><div className="invite-actions"><button className="share-primary" onClick={() => { navigator.clipboard?.writeText(inviteUrl()); notify('Invite link copied — send it to your friends!') }}>↗ <span>Copy invite link</span></button><button className="share-secondary" onClick={() => { navigator.clipboard?.writeText(code); notify('Room code copied') }}>▣ <span>Copy code</span></button></div><button className="enter-cinema" onClick={enterRoom}>Enter your cinema <span>→</span></button><button className="skip-link" onClick={enterRoom}>I’ll invite people later</button></section>{toast && <div className="toast-note">{toast}</div>}</main>

  if (screen === 'prejoin') return <main className="prejoin-page"><header className="simple-top"><button className="brand-mark" onClick={() => setScreen('home')}>◉ <span>social cinema</span></button><span className="step-note">YOU’RE ON THE LIST</span></header><section className="prejoin-card"><div className="preview-camera"><div className="preview-person"><div className="avatar art-violet">TN</div><span>Camera preview</span></div><span className="preview-status">● YOUR CAMERA IS {cam ? 'ON' : 'OFF'}</span></div><div className="eyebrow">PULL UP A SEAT</div><h1>{roomName}</h1><p>Hosted by <b>Tenzin</b> <span>·</span> <b>4 / {maxPeople} seats filled</b></p><div className="prejoin-toggles"><button onClick={() => setCam(!cam)}>{cam ? '▣' : '▧'} Camera <b>{cam ? 'On' : 'Off'}</b></button><button onClick={() => setMic(!mic)}>{mic ? '♫' : '♩'} Microphone <b>{mic ? 'On' : 'Off'}</b></button></div><button className="create-submit" onClick={enterRoom}>Join cinema <span>→</span></button><button className="skip-link" onClick={() => { setCam(false); setMic(false); enterRoom() }}>Join without camera or mic</button></section>{toast && <div className="toast-note">{toast}</div>}</main>

  if (screen === 'join') return <main className="invite-page"><header className="simple-top"><button className="brand-mark" onClick={() => setScreen('home')}>◉ <span>social cinema</span></button><span className="step-note">YOUR PEOPLE SAVED YOU A SEAT</span></header><section className="invite-card join-code-card"><div className="success-orbit">⌁</div><span className="eyebrow">COME ON IN</span><h1>Join a cinema.</h1><p>Enter the room code from your invite. Your friends are saving you the good seat.</p><label className="code-input-label">ROOM CODE<input autoFocus value={joinCode} maxLength={6} placeholder="E.G. AB7K92" onChange={(event) => setJoinCode(event.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ''))}/></label><button className="enter-cinema" disabled={joinCode.length !== 6} onClick={() => { setCode(joinCode); setRoomName('Friday Night Movie 🍿'); setScreen('prejoin') }}>Find my cinema <span>→</span></button><button className="skip-link" onClick={() => setScreen('home')}>← Back to home</button></section>{toast && <div className="toast-note">{toast}</div>}</main>

  return <main className="home-page"><header className="home-top"><button className="brand-mark"><span className="brand-symbol">◉</span><span>social cinema</span></button><div className="home-profile"><button className="help-link" onClick={() => notify('Your cinema guide is coming soon')}>How it works <span>↗</span></button><button className="avatar profile-avatar art-violet" onClick={() => notify('Profile settings coming soon')}>TN</button></div></header><section className="welcome-row"><div><span className="eyebrow">THURSDAY, SEPTEMBER 25</span><h1>Evenings are better <span>together.</span></h1><p>Your people, your movie, one little corner of the internet.</p></div><div className="welcome-popcorn">✦</div></section><section className="hero-actions"><button className="action-card create-card" onClick={() => setScreen('create')}><span className="card-icon">✳</span><span className="action-eyebrow">START A WATCH PARTY</span><b>Create a cinema</b><small>Pick a film and invite your favorite people.</small><span className="card-arrow">↗</span><span className="card-glow"/></button><button className="action-card join-card" onClick={() => setScreen('join')}><span className="card-icon">⌁</span><span className="action-eyebrow">GOT AN INVITE?</span><b>Join a cinema</b><small>Grab your seat. The previews are on.</small><span className="card-arrow">↗</span></button></section><div className="section-heading"><div><span className="eyebrow">PICK UP WHERE YOU LEFT OFF</span><h2>Recent cinemas</h2></div><button className="see-all" onClick={() => notify('You’re all caught up')}>See all <span>→</span></button></div><section className="recent-card"><div className="recent-art"><div className="film-art bunny"><span>BUNNY</span><b>▶</b></div><span className="recent-time">LAST WATCHED 2 DAYS AGO</span></div><div className="recent-details"><div className="recent-title"><div><span className="room-pill"><i/> CINEMA</span><h3>Sunday comfort movies</h3><p>Big Buck Bunny <span>·</span> with Maya, Ethan + 1</p></div><button className="recent-more" onClick={() => notify('Room is closed. Start a new cinema to watch again.')}>•••</button></div><div className="recent-footer"><div className="avatar-stack"><span className="mini-avatar art-coral">MC</span><span className="mini-avatar art-blue">EB</span><span className="mini-avatar art-gold">JR</span><span className="stack-count">+1</span></div><button className="reopen-button" onClick={() => { setRoomName('Sunday comfort movies'); setFilm(films[0]); setScreen('prejoin') }}>Watch again <span>→</span></button></div></div></section><footer className="home-footer"><span>◉ <b>SOCIAL CINEMA</b></span><span>Make room for a little togetherness.</span><span className="footer-status"><i/> All systems cozy</span></footer>{toast && <div className="toast-note">{toast}</div>}</main>
}

export default App
